apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-app
  template:
    metadata:
      labels:
        app: pizza-app
    spec:
      containers:
      - name: pizza-app
        image: pizza-app:latest  # Use the local image name
        imagePullPolicy: Never  # Prevent Kubernetes from trying to pull the image from a registry
        ports:
        - containerPort: 8080