apiVersion: v1
kind: Service
metadata:
  name: pizza-app-service
spec:
  selector:
    app: pizza-app  # Match labels from deployment
  ports:
    - protocol: TCP
      port: 80       # External port for accessing the service
      targetPort: 8080  # Port inside the container
  type: NodePort     # Expose service on a node port for local access